name: CI Pipeline  # Workflow name

on:
  push:            # Trigger workflow on code push
    branches:
      - main       # Runs only on the 'main' branch

jobs:
  build:           # Job 1: Build the project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code       # Step 1: Pull the latest code
        uses: actions/checkout@v3

      - name: Set up Node.js      # Step 2: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies  # Step 3: Install project dependencies
        run: |
          npm install
          echo "Dependencies installed!"

      - name: Run tests           # Step 4: Run tests
        run: |
          echo "Running tests..."
          npm test                # Replace with real test command
