name: CI Pipeline  # Name of the workflow

on:
  push:            # Trigger workflow on push
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for access

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test
