name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pulls your repository's code

      - name: Validate Markdown Files
        run: |
          echo "Checking Markdown files..."
          if [ -z "$(find . -name '*.md')" ]; then
            echo "No Markdown files found."
          else
            echo "Markdown files exist. All good!"
          fi

      - name: Success message
        run: |
          echo "Workflow completed successfully. CI is running fine!"
